apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth

spec:
  replicas: 2

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
      - name: auth

        image: 008266478986.dkr.ecr.us-east-1.amazonaws.com/toggle-master-repo-0:latest

        ports:
          - containerPort: 8080
