apiVersion: apps/v1
kind: Deployment

metadata:
  name: targeting

spec:
  replicas: 2

  selector:
    matchLabels:
      app: targeting

  template:
    metadata:
      labels:
        app: targeting

    spec:
      containers:
      - name: targeting

        image: 008266478986.dkr.ecr.us-east-1.amazonaws.com/toggle-master-repo-2:latest

        ports:
        - containerPort: 8082
