apiVersion: apps/v1
kind: Deployment

metadata:
  name: evaluation

spec:
  replicas: 2

  selector:
    matchLabels:
      app: evaluation

  template:
    metadata:
      labels:
        app: evaluation

    spec:
      containers:
      - name: evaluation

        image: 008266478986.dkr.ecr.us-east-1.amazonaws.com/toggle-master-repo-3:latest

        ports:
        - containerPort: 8083
