apiVersion: apps/v1
kind: Deployment

metadata:
  name: flag

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flag

  template:
    metadata:
      labels:
        app: flag

    spec:
      containers:
      - name: flag

        image: 008266478986.dkr.ecr.us-east-1.amazonaws.com/toggle-master-repo-1:latest

        ports:
        - containerPort: 8081
